import 'package:get/get.dart';
import 'package:irhib/ui/home/pages/favorite_page.dart';

class MyLocal implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en": {
          "welcome": "Welcome",
          "signin": "Sign In",
          "username": "user name",
          "userhint": "amany abu nada",
          "password": "Password",
          "forgetpassword": "forget password?",
          "login": "LogIn",
          "noaccount": "Dont have an account?",
          "creataccount": "Creat Account",
          "country": "Country",
          "phonenumber": "Phone Number",
          "email": "Email Address",
          "have account": "I have an account?",
          "city": "City",
          "license": "License",
          "government document": "Government Document",
          "Service provider type": "Service Provider Type",
          "location": "Location",
          "next": "Next",
          "home": "Home",
          "favorite": "Favorite",
          "explore": "Explore",
          "profile": "Profile",
          "search": "Search",
          "populerCity": "Populer City",
          "more": "More",
          "inbox": "Inbox",
          "privacy policy": "Privacy Policy",
          "about app": "About App",
          "precautionary conditions": "Precautionary Conditions",
          "language": "Language",
          "logout": "Logout",
          "toure_guides": "Toure Guides",
          "service_providers": "Service Provider",
          "add_tripe": "Add Tripe",
          "populer_trips": "Populer Trips",
          "tripe_details": "Trip Details",
        },
        "ar": {
          "welcome": "أهلا بك",
          "signin": "قم بتسجيل الدخول ",
          "username": "اسم المستخدم",
          "userhint": "اماني أبو ندى",
          "password": " كلمة المرور",
          "forgetpassword": "نسيت كلمة السر؟",
          "login": "تسجيل الدخول",
          "noaccount": "ليس لديك حساب؟",
          "creataccount": "انشاء حساب",
          "country": "الدولة",
          "phonenumber": "رقم الجوال",
          "email": " البريد الالكتروني",
          "have account": "لدي حساب؟",
          "city": "المدينة",
          "license": "ترخيص",
          "government document": "وثيقة حكومية",
          "Service provider type": "نوع مزود الخدمة",
          "location": "الموقع",
          "next": "التالي",
          "home": "الرئيسية",
          "favorite": "المفضلة",
          "explore": "اكتشف",
          "profile": "الملف الشخصي",
          "search": "بحث",
          "populerCity": "أشهر المدن",
          "more": "المزيد",
          "inbox": "صندوق الوارد",
          "privacy policy": "سياسة الخصوصية",
          "about app": "حول التطبيق",
          "precautionary conditions": "الشروط الوقائية",
          "language": "اللغة",
          "logout": "تسجيل الخروج",
          "toure_guides": "مرشدين سياحين",
          "service_providers": "مزودين الخدمة",
          "add_tripe": "اضافة رحلة",
          "populer_trips": "أشهر الرحلات",
          "tripe_details": "تفاصيل الرحلة",
        },
      };
}
